version: '3.2'

networks:
  im-network:
    driver: bridge

volumes:
  prometheus_data: {}
services:
  im-mysql:
    image: mysql:5.7
    container_name: im-mysql
    volumes:
    - ./data/db_data:/var/lib/mysql
    - ./config/mysql/init:/docker-entrypoint-initdb.d/
    command: [
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci',
      '--default-time-zone=+8:00'
    ]
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: im
      MYSQL_USER: lyzzcw
      MYSQL_PASSWORD: lyzzcw
    ports:
    - 3306:3306
    networks:
    - im-network

  im-redis:
    container_name: im-redis
    image: redislabs/redismod:latest
    ports:
    - 6379:6379
    networks:
    - im-network
#  im-redis-commander:
#    container_name: im-redis-commander
#    hostname: im-redis-commander
#    image: rediscommander/redis-commander:latest
#    environment:
#    - REDIS_HOSTS=local:im-redis:6379
#    ports:
#    - 8083:8081
#    networks:
#    - im-network
  im-rmqnamesrv:
    image: apache/rocketmq:4.9.0
    container_name: im-rmqnamesrv
    ports:
      - 9876:9876
    volumes:
      - ./data/rocketmq/logs:/home/rocketmq/logs
      - ./data/rocketmq/store:/home/rocketmq/store
    command: sh mqnamesrv
    networks:
      - im-network
  im-rmqbroker:
    image: apache/rocketmq:4.9.0
    container_name: im-rmqbroker
    ports:
      - 10909:10909
      - 10911:10911
      - 10912:10912
    volumes:
      - ./data/rocketmq/logs:/home/rocketmq/logs
      - ./data/rocketmq/store:/home/rocketmq/store
      - ./config/rocketmq/broker.conf:/home/rocketmq/rocketmq-4.9.0/conf/broker.conf
    command: sh mqbroker -n im-rmqnamesrv:9876 -c ../conf/broker.conf autoCreateTopicEnable=true &
    depends_on:
      - im-rmqnamesrv
    environment:
      JAVA_OPT_EXT: "-server -Xms512m -Xmx512m -Xmn256m"
    networks:
      - im-network
  im-rmqconsole:
    image: styletang/rocketmq-console-ng:latest
    container_name: im-rocketmq-console
    ports:
      - 8076:8080
    depends_on:
      - im-rmqnamesrv
    environment:
      - JAVA_OPTS= -Dlogging.level.root=info  -Drocketmq.namesrv.addr=im-rmqnamesrv:9876
      - Dcom.rocketmq.sendMessageWithVIPChannel=false
    networks:
      - im-network

  im-elasticsearch:
    image: elasticsearch:7.14.2
    container_name: im-elasticsearch
    volumes:
    - ./config/elk/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
    - "9200:9200"
    - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      discovery.type: single-node
    networks:
    - im-network

  im-logstash:
    image: logstash:7.14.2
    container_name: im-logstash
    volumes:
    - ./config/elk/logstash.yml:/usr/share/logstash/config/logstash.yml
    - ./config/elk/pipeline:/usr/share/logstash/pipeline
    ports:
    - "5044:5044"
    - "5000:5000/tcp"
    - "5000:5000/udp"
    - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
    - im-network
    depends_on:
    - im-elasticsearch

  im-kibana:
    image: kibana:7.14.2
    container_name: im-kibana
    volumes:
    - ./config/elk/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
    - "5601:5601"
    networks:
    - im-network
    depends_on:
    - im-elasticsearch

  im-sentinel:
    image: bladex/sentinel-dashboard
    container_name: im-sentinel
    ports:
      - 8858:8858
    networks:
      - im-network

  im-nacos:
    image: nacos/nacos-server:2.0.3
    container_name: im-nacos-standalone-mysql
    env_file:
    - ./config/nacos/nacos-standlone-mysql.env
    volumes:
    - ./data/nacos_logs/:/home/nacos/logs
    - ./config/nacos/custom.properties:/home/nacos/init.d/custom.properties
    ports:
    - 8848:8848
    - 9848:9848
    - 9555:9555
    depends_on:
    - im-mysql
#    restart: on-failure
    networks:
    - im-network


